[project]
name = "grid_erp"
authors = [
    {name = "Calco PolyTechnik Pvt Ltd", email = "mis.1@calco.in"}
]
description = "Calco PolyTechnik Manufacturing ERP - Branding, WhatsApp and Recruitment Assessment"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "grid_erp"
